# Thông tin kết nối SQL Server (Sửa lại port 1433 và tên DB EquineCareDB nếu khác)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EquineCareDB;encrypt=true;trustServerCertificate=true
# Điền Username và Password vào máy chủ SQL Server của bạn (VD: sa / 123456)
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Đổi port của Server nếu port 8080 đang bị chiếm (tùy chọn)
server.port=8080